spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: merchant-service
              uri: lb://merchant-service
              predicates:
                - Path=/merchants/**

            - id: auth-service
              uri: lb://merchant-service
              predicates:
                - Path=/auth/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/